### ISSUE TITLE
More usage examples

### ISSUE THREAD

**Issue by falkamelung** [bakerunavco/SSARA#4]
It would be nice if working usage examples for all supported archives/satellites could be provided when running "ssara_federated_query.py". Currently it just shows examples for ESA data. Does it really work for ASF ALOS data? How to access DLR Supersite data? How to access UAVSAR data? How to access CSK collections in the Unavco data sharing system?

**Comment by bakerunavco** [comment]
I added a new wiki page with [Usage Examples](../wiki/Usage-Examples).
