### ISSUE TITLE
Meaningful kml filename

### ISSUE THREAD

**Issue by yunjunz** [bakerunavco/SSARA#7]
I usually use --kml option to see the availability and coverage for my dataset of interest, and need to change the kml file name every time after the search. It will be more convenient if SSARA could give a more meaningful filename, like S1A_ASF_R3F616S20160101E20160301_20160520212828.kml.

**Comment by bakerunavco** [comment]
Added a option to specify the KML name on the command line so that you don't need to rename after the search.  This is better than hardwiring a more "meaningful" name into the code.
