### ISSUE TITLE
Problem in Downloading from Supersite VA4

### ISSUE THREAD

**Issue by mohseniaref** [bakerunavco/SSARA#8]
Hi

The SSARA script just can create data linke with 74 KB space.however I can download data manually without any problem.

Would you please guide me how to solve this problem.

best regards,
Mohammad

 ssara_federated_query.py --relativeOrbit 364 --frame 2835  --print --download --parallel=1
Running SSARA API Query
SSARA API query: 2.787526 seconds
Found 23 scenes
Scenes after filtering for monthMin 1 and monthMax 12: 23
Supersites VA4,ENVISAT,6931,2003-06-28 07:16:27,2003-06-28 07:16:44,364,2835,2835,IM,S2,D,R,VV,https://eo-virtual-archive4.esa.int/supersites/ASA_IM__0CNPDK20030628_071627_000000172017_00364_06931_0026.N1

**Comment by bakerunavco** [comment]
There was an update to the secp script used for downloading from VA4, so you might need to update your local repo with a git pull.
